#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : XStatic-mdi
Version  : 1.6.50.2
Release  : 16
URL      : https://files.pythonhosted.org/packages/1c/02/fb6e654eca3486fd74a80a51aada0e621225193957b0e5b97dc157c57c32/XStatic-mdi-1.6.50.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/1c/02/fb6e654eca3486fd74a80a51aada0e621225193957b0e5b97dc157c57c32/XStatic-mdi-1.6.50.2.tar.gz
Summary  : mdi 1.6.50 (XStatic packaging standard)
Group    : Development/Tools
License  : OFL-1.1
Requires: XStatic-mdi-python = %{version}-%{release}
Requires: XStatic-mdi-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
XStatic-mdi
        -----------
        
        mdi javascript library packaged for setuptools (easy_install) / pip.
        
        This package is intended to be used by **any** project that needs these files.
        
        It intentionally does **not** provide any extra code except some metadata
        **nor** has any extra requirements. You MAY use some minimal support code from
        the XStatic base package, if you like.
        
        You can find more info about the xstatic packaging way in the package
        `XStatic`.

%package python
Summary: python components for the XStatic-mdi package.
Group: Default
Requires: XStatic-mdi-python3 = %{version}-%{release}
Provides: xstatic-mdi-python

%description python
python components for the XStatic-mdi package.


%package python3
Summary: python3 components for the XStatic-mdi package.
Group: Default
Requires: python3-core

%description python3
python3 components for the XStatic-mdi package.


%prep
%setup -q -n XStatic-mdi-1.6.50.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570210936
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
